apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-external-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
  type: LoadBalancer